print('Hello M.6/14')
print('Pumipat')
print('Sripaipot')
print('Chonrasadornumrung School')
print('17 years old')
print('178 cm.')
print('90 kg.')
print('male')
print('favorite color is blue')
print('once')
#นายภูมิพัฒน์ ศรีไพพจน์ 19